### ISSUE TITLE
Requirements are too hard

### ISSUE THREAD

**Issue by lcrmorin** [Spectral-Finance/challenge-1-modeler-starter-kit#3]
Currently the client requires python >= 3.11.6 which is not commonly available on DS platform (Kaggle/Collab) that are stuck at 3.10.12. This largely prevents me from participating. Additionnaly the requirements.txt seems quite long (166 lines). 
Could you loosen that python version constraint ? and clean the requirement file ?

**Comment by ZanePeycke** [comment]
Hi Lucas, 3.11.6 is a requirement for the zkml proofs tooling we're using so we are unable to downgrade that. We tested on 3.10 versions and were unable to complete core steps of the challenge process, so using a lower version is not an option. To get around this I would suggest working on some instance where you have control of the python version. 

On the long requirements.txt file, you may choose to start by only installing spectral-cli and install other packages as you see fit. However, spectral-cli does have a number of necessary requirements as well. By installing only spectral-cli you can download the training dataset and start working. If you choose to make a submission to this challenge other libraries that are in the requirements file like Pytorch, spectral-datawrappers, etc. will be required.
